### ISSUE TITLE
MySQL-kafka incr stage: MySQL executes the delete statement without sending all records to kafka

### ISSUE THREAD

**Issue by asiroliu** [actiontech/dtle#1008]
## Description
MySQL-kafka incr stage: MySQL executes the delete statement without sending all records to kafka

## Steps to reproduce the issue
1. src MySQL create database and table
```sql
sql> CREATE DATABASE IF NOT EXISTS `action_db`;
sql> create table bit_1_columns(id int(11) not null primary key, c_bit_1 bit(1) DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
2. create MySQL-Kafka job
```json
{
  "job_id": "data_types_default_incr_bit_1_columns",
  "is_password_encrypted": false,
  "task_step_name": "all",
  "failover": true,
  "retry": 2,
  "src_task": {
    "task_name": "src",
    "node_id": "a5837594-2241-b503-56ab-645460d64106",
    "mysql_src_task_config": {
      "gtid": "",
      "binlog_relay": false
    },
    "drop_table_if_exists": true,
    "skip_create_db_table": false,
    "repl_chan_buffer_size": 120,
    "chunk_size": 2000,
    "group_max_size": 1,
    "group_timeout": 100,
    "connection_config": {
      "database_type": "MySQL",
      "host": "172.100.9.3",
      "port": 3306,
      "user": "test_src",
      "password": "test_src"
    },
    "replicate_do_db": [
      {
        "table_schema": "action_db",
        "tables": [
          {
            "table_name": "bit_1_columns"
          }
        ]
      }
    ]
  },
  "dest_task": {
    "task_name": "dest",
    "node_id": "f31dc051-c5a1-f900-0bed-d39d45548898",
    "parallel_workers": 1,
    "kafka_topic": "dtle",
    "kafka_broker_addrs": [
      "172.100.9.21:9092"
    ]
  }
```
3. src MySQL execute sql
```sql
insert into bit_1_columns values (0,0);
insert into bit_1_columns values (1,1);
insert into bit_1_columns values (2,NULL);
update bit_1_columns set c_bit_1=NULL where id = 0;
update bit_1_columns set c_bit_1=0 where id = 1;
update bit_1_columns set c_bit_1=1 where id = 2;
delete from bit_1_columns;
``` 
4. compare kafka message with dbz
[bit_1_columns.html.txt](https://github.com/actiontech/dtle/files/9080565/bit_1_columns.html.txt)

## Describe the results you received
DTLE job only send one delete record to the kafka

## Describe the results you expected
DTLE job only send all delete record to the kafka

## Output of `./dtle version`:**

```
9.9.9.9-master-3784044
```

**Comment by asiroliu** [comment]
修复后有panic
```
2022-07-19T10:49:32.735+0800 [DEBUG] client.driver_mgr.dtle: incr. after publish nats reply.: driver=dtle @module=dtle.kafka job=data_types_default_incr_char_columns-subscription timestamp=2022-07-19T10:49:32.735+0800
2022-07-19T10:49:32.735+0800 [DEBUG] client.driver_mgr.dtle: incr. send by GroupLimit: driver=dtle @module=dtle.kafka Entries.len=1 MessageGroupMaxSize=1 entriesSize=1077 job=data_types_default_incr_char_columns-subscription timestamp=2022-07-19T10:49:32.735+0800
2022-07-19T10:49:32.735+0800 [DEBUG] client.driver_mgr.dtle: kafkaTransformDMLEventQueries: driver=dtle @module=dtle.kafka gno=11 job=data_types_default_incr_char_columns-subscription timestamp=2022-07-19T10:49:32.735+0800
2022-07-19T10:49:32.736+0800 [DEBUG] client.driver_mgr.dtle: new table info: driver=dtle @module=dtle.kafka job=data_types_default_incr_char_columns-subscription schemaName=action_db tableName=char_columns timestamp=2022-07-19T10:49:32.735+0800
2022-07-19T10:49:32.738+0800 [DEBUG] client.driver_mgr.dtle: panic: runtime error: invalid memory address or nil pointer dereference: driver=dtle
2022-07-19T10:49:32.738+0800 [DEBUG] client.driver_mgr.dtle: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x281ab8c]: driver=dtle
2022-07-19T10:49:32.738+0800 [DEBUG] client.driver_mgr.dtle: : driver=dtle
2022-07-19T10:49:32.738+0800 [DEBUG] client.driver_mgr.dtle: goroutine 594 [running]:: driver=dtle
2022-07-19T10:49:32.738+0800 [DEBUG] client.driver_mgr.dtle: [github.com/actiontech/dtle/driver/kafka.(*KafkaRunner).kafkaTransformDMLEventQueries](http://github.com/actiontech/dtle/driver/kafka.(*KafkaRunner).kafkaTransformDMLEventQueries)(0xc003b3ec80, 0xc000624390, 0x1, 0x1, 0xc000000002, 0x314e2e2): driver=dtle
2022-07-19T10:49:32.738+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/[github.com/actiontech/dtle/driver/kafka/kafka3.go:949](http://github.com/actiontech/dtle/driver/kafka/kafka3.go:949) +0x18c: driver=dtle
2022-07-19T10:49:32.738+0800 [DEBUG] client.driver_mgr.dtle: [github.com/actiontech/dtle/driver/kafka.(*KafkaRunner).handleIncr.func1](http://github.com/actiontech/dtle/driver/kafka.(*KafkaRunner).handleIncr.func1)(0xc000d47c80, 0x314e2e2): driver=dtle
2022-07-19T10:49:32.738+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/[github.com/actiontech/dtle/driver/kafka/kafka3.go:435](http://github.com/actiontech/dtle/driver/kafka/kafka3.go:435) +0x68: driver=dtle
2022-07-19T10:49:32.738+0800 [DEBUG] client.driver_mgr.dtle: [github.com/actiontech/dtle/driver/kafka.(*KafkaRunner).handleIncr(0xc003b3ec80)](http://github.com/actiontech/dtle/driver/kafka.(*KafkaRunner).handleIncr(0xc003b3ec80)): driver=dtle
2022-07-19T10:49:32.738+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/[github.com/actiontech/dtle/driver/kafka/kafka3.go:497](http://github.com/actiontech/dtle/driver/kafka/kafka3.go:497) +0x745: driver=dtle
2022-07-19T10:49:32.738+0800 [DEBUG] client.driver_mgr.dtle: created by [github.com/actiontech/dtle/driver/kafka.(*KafkaRunner).initiateStreaming](http://github.com/actiontech/dtle/driver/kafka.(*KafkaRunner).initiateStreaming): driver=dtle
2022-07-19T10:49:32.738+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/[github.com/actiontech/dtle/driver/kafka/kafka3.go:512](http://github.com/actiontech/dtle/driver/kafka/kafka3.go:512) +0xd5: driver=dtle
2022-07-19T10:49:32.748+0800 [ERROR] client.driver_mgr: error receiving stream from TaskStats driver RPC, closing stream: driver=dtle error="rpc error: code = Unavailable desc = transport is closing"
2022-07-19T10:49:32.748+0800 [DEBUG] client.driver_mgr.stdio: received EOF, stopping recv loop: driver=dtle err="rpc error: code = Unavailable desc = transport is closing"
2022-07-19T10:49:32.748+0800 [DEBUG] client.driver_mgr: plugin process exited: driver=dtle path=/opt/dtle/usr/share/dtle/nomad-plugin/dtle pid=332 error="exit status 2"
2022-07-19T10:49:32.748+0800 [DEBUG] client.alloc_runner.task_runner: driver plugin has shutdown; attempting to recover task: alloc_id=49d2897c-444b-8d07-75d6-a0d5265d37fd task=dest driver=dtle
2022-07-19T10:49:32.748+0800 [WARN]  client.driver_mgr: received fingerprint error from driver: driver=dtle error="plugin is shut down"
2022-07-19T10:49:32.748+0800 [WARN]  client.driver_mgr: failed to reattach to plugin, starting new instance: driver=dtle err="singleton plugin exited"
```
