### ISSUE TITLE
While adding agent（client）node on the running 'scenario of reciprocating migration on the same table' lead to Panic on DTLE

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dtle#310]
**Description**

While adding an agent(client) DTLE on the running 'scenario of reciprocating migration on the same table' lead to Panic on DTLE

**Steps to reproduce the issue:**
1. Create job1 and job2 for the same empty table sbtest1 on two mysql instances ：

- [job1.txt](https://github.com/actiontech/dtle/files/2378177/job1.txt)

- [job2.txt](https://github.com/actiontech/dtle/files/2378178/job2.txt)

2. Insert 10 records through the src of job1 and job2 respectively by sysbench 

`/opt/sysbench0.5/bin/sysbench  --test=/opt/sysbench0.5/db/oltp.lua --report-interval=10 --oltp-tables-count=1 --num-threads=1 --oltp-table-size=10 --mysql-user=test --mysql-password=test --mysql-db=sbtest --mysql-port=2222 --mysql-host=10.186.30.144 prepare`

`/opt/sysbench0.5/bin/sysbench  --test=/opt/sysbench0.5/db/oltp.lua --report-interval=10 --oltp-tables-count=1 --num-threads=1 --oltp-table-size=10 --mysql-user=test --mysql-password=test --mysql-db=sbtest --mysql-port=4444 --mysql-host=10.186.30.108 prepare`

3. Add a DTLE as an agent while the job1 is running through sysbench run

`/opt/sysbench0.5/bin/sysbench  --test=/opt/sysbench0.5/db/oltp.lua --report-interval=10 --oltp-tables-count=1 --num-threads=1 --oltp-table-size=10 --mysql-user=test --mysql-password=test --mysql-db=sbtest --mysql-port=4444 --mysql-host=10.186.30.108 run`

**Describe the results you received:**

The Existing DTLE panic

**Describe the results you expected:**

The same table of reciprocating migration scenarios should support adding an agent DTLE

**Output of `./dtle version`:**

```
Dtle 9.9.9.9 (git: master bbabd4f89d2b1f72f51fdac1d516a954119bbb2c)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

*Dtle Background: One node Dtle as both manager and agent*

1. manager DTLE config:
```
# Setup data dir
data_dir = "/opt/udup/data"
log_file = "/opt/udup/var/log/udup/udup.log"
log_level = "DEBUG"
bind_addr = "10.186.30.4"
log_to_stdout = true

ui = true
ui_dir = "/opt/udup-frontend-master"

# Modify our port to avoid a collision with server
ports {
    http = 8190
}

# Enable the manager
manager {
    enabled = true

    # Self-elect, should be 3 or 5 for production,
    # Addresses to attempt to join when the server starts.
    join = [ "10.186.30.4" ]
}

# Enable the agent
agent {
    enabled = true
    managers = ["10.186.30.4:8191"]
}

addresses {
  http = "10.186.30.4"
  rpc = "10.186.30.4"
  serf = "10.186.30.4"
}
advertise {
  http = "10.186.30.4"
  rpc = "10.186.30.4"
  serf = "10.186.30.4"
}
```

2.The config of the newly added DTLE:

```
# Setup data dir
data_dir = "/opt/udup/data"
log_file = "/opt/udup/var/log/udup/udup.log"
log_level = "DEBUG"
bind_addr = "10.186.30.119"
log_to_stdout = true

ui = true
ui_dir = "/opt/udup-frontend-master"

# Modify our port to avoid a collision with server
ports {
    http = 8190
}

# Enable the manager
manager {
    enabled = false

    # Self-elect, should be 3 or 5 for production,
    # Addresses to attempt to join when the server starts.
    join = [ "10.186.30.4" ]
}

# Enable the agent
agent {
    enabled = true
    managers = ["10.186.30.4:8191"]
}

addresses {
  http = "10.186.30.119"
  rpc = "10.186.30.119"
  serf = "10.186.30.119"
}
advertise {
  http = "10.186.30.119"
  rpc = "10.186.30.119"
  serf = "10.186.30.119"
}
```

**Additional details (log, config, job config etc):**

- The newly added agent DTLE:
```
[root@119 udup]# /opt/udup/usr/bin/udup server -config=/opt/udup/etc/udup/udup.conf 
2018/09/13 16:31:25.999079 [INFO] Loaded configuration from /opt/udup/etc/udup/udup.conf 
2018/09/13 16:31:25.999485 [INFO] Starting Udup server... 
2018/09/13 16:31:26.000138 [INFO] agent: Using state directory /opt/udup/data/agent 
2018/09/13 16:31:26.004084 [DEBUG] agent: Starting nats streaming server [0.0.0.0:8193] 
2018/09/13 16:31:26.284995 [DEBUG] agent: Available drivers [MySQL] 
2018/09/13 16:31:26.285104 [INFO] agent: Node ID "22ce77ff-4e76-2222-1e35-e9393c7a933b" 
2018/09/13 16:31:26.285564 [INFO] Udup server configuration:
 
2018/09/13 16:31:26.285586 [INFO]               Agent: true 
2018/09/13 16:31:26.285596 [INFO]           Log Level: DEBUG 
2018/09/13 16:31:26.285607 [INFO]             Manager: false 
2018/09/13 16:31:26.285617 [INFO]             Version: 9.9.9.9 
2018/09/13 16:31:26.285626 [INFO] Udup server started! Log data will stream in below:
 
2018/09/13 16:31:26.286273 [DEBUG] agent: RPC failed to server 10.186.30.4:8191: rpc error: failed to get conn: dial tcp 10.186.30.4:8191: connect: connection refused 
2018/09/13 16:31:26.286354 [ERR] agent: Registration failure: 1 error occurred:
  * RPC failed to server 10.186.30.4:8191: rpc error: failed to get conn: dial tcp 10.186.30.4:8191: connect: connection refused

 
2018/09/13 16:31:41.286047 [DEBUG] agent: RPC failed to server 10.186.30.4:8191: rpc error: failed to get conn: dial tcp 10.186.30.4:8191: connect: connection refused 
2018/09/13 16:31:41.286088 [ERR] agent: Failed to query for node allocations: 1 error occurred:
  * RPC failed to server 10.186.30.4:8191: rpc error: failed to get conn: dial tcp 10.186.30.4:8191: connect: connection refused

```

- Panic DTLE:
```
2018/09/13 16:31:20.796122 [DEBUG] [dc426bf4-fe5b-90c1-34b0-0e9a804bd242] mysql.applier: a binlogEntry MTS enqueue. gno: 5571 
2018/09/13 16:31:20.796130 [DEBUG] [dc426bf4-fe5b-90c1-34b0-0e9a804bd242] mysql.applier: a binlogEntry. remaining: 39. gno: 5572, lc: 5571, seq: 5572 
2018/09/13 16:31:20.796138 [DEBUG] [dc426bf4-fe5b-90c1-34b0-0e9a804bd242] mysql.applier: a binlogEntry MTS dequeue, worker: 0 
2018/09/13 16:31:20.796199 [DEBUG] [110c5986-ce7b-4384-8b67-c599e70ffea0] mysql.reader: query event: schema: , query: BEGIN 
2018/09/13 16:31:20.796217 [DEBUG] [110c5986-ce7b-4384-8b67-c599e70ffea0] extractor. incr. send by GroupLimit: 1 
2018/09/13 16:31:20.796242 [DEBUG] [dc426bf4-fe5b-90c1-34b0-0e9a804bd242] ApplyBinlogEvent. insert gno: 5571 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xe42928]

goroutine 1783271 [running]:
udup/internal/config/mysql.(*ColumnList).Len(...)
  /universe/src/udup/internal/config/mysql/types.go:255
udup/internal/client/driver/mysql/sql.BuildDMLUpdateQuery(0xc42249cd80, 0x6, 0xc42249cd86, 0x7, 0x0, 0x0, 0x0, 0x0, 0xc42744f720, 0x4, ...)
  /universe/src/udup/internal/client/driver/mysql/sql/builder.go:233 +0x58
udup/internal/client/driver/mysql.(*Applier).buildDMLEventQuery(0xc42334ae00, 0x0, 0x0, 0x0, 0x0, 0xc42249cd80, 0x6, 0xc42249cd86, 0x7, 0xc42249cd90, ...)
  /universe/src/udup/internal/client/driver/mysql/applier.go:1045 +0x296
udup/internal/client/driver/mysql.(*Applier).ApplyBinlogEvent(0xc42334ae00, 0x0, 0xc421f67400, 0x0, 0x0)
  /universe/src/udup/internal/client/driver/mysql/applier.go:1141 +0x1020
udup/internal/client/driver/mysql.(*Applier).MtsWorker(0xc42334ae00, 0x0)
  /universe/src/udup/internal/client/driver/mysql/applier.go:273 +0x1e6
created by udup/internal/client/driver/mysql.(*Applier).Run
  /universe/src/udup/internal/client/driver/mysql/applier.go:315 +0x1eb

```

**Comment by Dinosauria** [comment]
> Version: Dtle 9.9.9.9 (git: master [9538076](https://github.com/actiontech/dtle/commit/9538076ecc8bb183712cf5829dc314ce93adc9f7))
> 
> On the beginning of executing sysbench run job1, job2 immediately becomes stopped,but **no more panic happened again** in this version
> 
> The checksum value of the src and dest target table of job1 is the same soon after the end of sysbench run.
> 
> Once resume job2 the value of checksum table will always in changing
> 
> Client DTLE is successfully added

In `Dtle 9.9.9.9 (git: master a79f36654cd7727b3987f1c262b44a8c50c1c3d1)`:
1. No panic
2. job2 keep running while executing sysbench run on job1, and the value of checksum table all the same in job1 and job2 soon after sysbench finish run.
3. Client DTLE is successfully added
