### ISSUE TITLE
Panic with sql 'alter table xx rename xxx'

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dtle#419]
**Description**

Panic with sql 'alter table xx rename xxx'

**Steps to reproduce the issue:**

1. do as issue steps in #355 

**Describe the results you received:**

Dtle panic with error

**Describe the results you expected:**

```
2019/03/20 14:10:15.162854 [DEBUG] [jobid:b5f6ace7-11ae-e438-cf12-5c115cfa826e] mysql.applier: no binlogEntry for 10s 
2019/03/20 14:10:20.552460 [DEBUG] [jobid:b5f6ace7-11ae-e438-cf12-5c115cfa826e] mysql.reader: query event: schema: testddl, query: alter table sbtest1 rename testrename 
2019/03/20 14:10:20.558428 [DEBUG] [jobid:b5f6ace7-11ae-e438-cf12-5c115cfa826e] mysql.reader: ddl is alter table. specs: [0xc000542000] 
2019/03/20 14:10:20.558466 [WARN] [jobid:b5f6ace7-11ae-e438-cf12-5c115cfa826e] error handle create table in binlog: GetTableColumns: table does not exists in sqle context. table: testddl.sbtest1 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x89e3c6]

goroutine 529 [running]:
github.com/actiontech/dtle/internal/config/mysql.(*ColumnList).Names(0x0, 0xc0000aa000, 0x73, 0xc0000aa000)
	/universe/src/github.com/actiontech/dtle/internal/config/mysql/types.go:192 +0x26
github.com/actiontech/dtle/internal/config/mysql.(*ColumnList).String(0x0, 0x16a20b1, 0x38)
	/universe/src/github.com/actiontech/dtle/internal/config/mysql/types.go:240 +0x2b
github.com/actiontech/dtle/internal/client/driver/mysql/binlog.(*BinlogReader).handleEvent.func1(0xc000d86be0, 0x168c2ff)
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/binlog/binlog_reader.go:407 +0xe9
github.com/actiontech/dtle/internal/client/driver/mysql/binlog.(*BinlogReader).handleEvent(0xc00073af00, 0xc000e4b140, 0xc000e18360, 0x0, 0x0)
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/binlog/binlog_reader.go:456 +0x11a7
github.com/actiontech/dtle/internal/client/driver/mysql/binlog.(*BinlogReader).DataStreamEvents(0xc00073af00, 0xc000e18360, 0xc000df5680, 0xc0004fe900)
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/binlog/binlog_reader.go:664 +0x210
github.com/actiontech/dtle/internal/client/driver/mysql.(*Extractor).StreamEvents(0xc000df5680, 0x167f3c6, 0x24)
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/extractor.go:804 +0x83
github.com/actiontech/dtle/internal/client/driver/mysql.(*Extractor).initiateStreaming.func1(0xc000df5680)
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/extractor.go:412 +0x66
created by github.com/actiontech/dtle/internal/client/driver/mysql.(*Extractor).initiateStreaming
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/extractor.go:410 +0x3f

```

**Output of `./dtle version`:**

```
Dtle 9.9.9.9 (git: master f09064f0e148822b4faa9ab75eb68ecf6ed46729)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

always

**Additional details (log, config, job config etc):**

other related issue： #300

**Comment by ffffwh** [comment]
It is renaming a table. We should
- clear table meta if ddl issued on this table
- get table meta when needed

**Comment by Dinosauria** [comment]
Verified in `Dtle 9.9.9.9 (git: master 3db3e66676698648183df520a653ba9a3a39d96c)`
