### ISSUE TITLE
Painc when prepare table by 'sysbench prepare'--instance level copy with all empty parameters

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dtle#428]
**Description**

Painc when prepare table by 'sysbench prepare'--instance level copy with all empty parameters

**Steps to reproduce the issue:**
1. POST a instance level copy ,which `ReplicateDoDb` as followings:
```
"ReplicateDoDb":[
    {
        "TableSchema":"",
        "TableSchemaRegex":"",
        "TableSchemaRename":"",
        "Tables":[
            {
                "TableName":"",
                "TableRegex":"",
                "TableRename":"",
                "where":"",
                "columns":[
                    {
                        "columnsRegex":"",
                        "columnsRename":""
                    }
                ]
            }
        ]
    }
],
```
2. Using sysbench prepare a table
3. dtle panic

**Describe the results you received:**
```
2019/04/01 19:44:22.347740 [DEBUG] [jobid:104f6a4a-f728-0326-6a76-65a2d69b6c92] mysql.applier: no binlogEntry for 10s 
2019/04/01 19:44:28.435262 [DEBUG] Worker.SaveState: lock: 0xc000be2c40, 0xc000b8dc00 
2019/04/01 19:44:28.435308 [DEBUG] Worker.SaveState: after lock: 0xc000be2c40 
2019/04/01 19:44:28.435315 [DEBUG] Worker.SaveState: after unlock: 0xc000be2c40 
2019/04/01 19:44:28.435410 [DEBUG] Worker.SaveState: lock: 0xc000c16770, 0xc000b8dbe0 
2019/04/01 19:44:28.435420 [DEBUG] Worker.SaveState: after lock: 0xc000c16770 
2019/04/01 19:44:28.435431 [DEBUG] Worker.SaveState: after unlock: 0xc000c16770 
2019/04/01 19:44:30.928021 [DEBUG] [jobid:104f6a4a-f728-0326-6a76-65a2d69b6c92] mysql.reader: query event: schema: test1, query: CREATE TABLE sbtest1 (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
k INTEGER UNSIGNED DEFAULT '0' NOT NULL,
c CHAR(120) DEFAULT '' NOT NULL,
pad CHAR(60) DEFAULT '' NOT NULL,
PRIMARY KEY (id)
) /*! ENGINE = innodb MAX_ROWS = 1000000 */ 
2019/04/01 19:44:30.928975 [DEBUG] [jobid:104f6a4a-f728-0326-6a76-65a2d69b6c92] mysql.reader: ddl is create table 
2019/04/01 19:44:30.928995 [WARN] [jobid:104f6a4a-f728-0326-6a76-65a2d69b6c92] error handle create table in binlog: GetTableColumns: table does not exists in sqle context. table: test1.sbtest1 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x89e3c6]

goroutine 611 [running]:
github.com/actiontech/dtle/internal/config/mysql.(*ColumnList).Names(0x0, 0xc0000aa000, 0x71, 0xc0000aa000)
	/universe/src/github.com/actiontech/dtle/internal/config/mysql/types.go:192 +0x26
github.com/actiontech/dtle/internal/config/mysql.(*ColumnList).String(0x0, 0x16a4022, 0x38)
	/universe/src/github.com/actiontech/dtle/internal/config/mysql/types.go:240 +0x2b
github.com/actiontech/dtle/internal/client/driver/mysql/binlog.(*BinlogReader).updateTableMeta(0xc000d46a80, 0x0, 0xc0004c03f7, 0x5, 0xc00013c1ed, 0x7, 0x7, 0x0)
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/binlog/binlog_reader.go:1410 +0xde
github.com/actiontech/dtle/internal/client/driver/mysql/binlog.(*BinlogReader).handleEvent(0xc000d46a80, 0xc00048a510, 0xc000b8be60, 0x0, 0x0)
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/binlog/binlog_reader.go:421 +0x1402
github.com/actiontech/dtle/internal/client/driver/mysql/binlog.(*BinlogReader).DataStreamEvents(0xc000d46a80, 0xc000b8be60, 0xc000c88240, 0xc00048ed20)
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/binlog/binlog_reader.go:675 +0x228
github.com/actiontech/dtle/internal/client/driver/mysql.(*Extractor).StreamEvents(0xc000c88240, 0x1681312, 0x24)
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/extractor.go:871 +0x83
github.com/actiontech/dtle/internal/client/driver/mysql.(*Extractor).initiateStreaming.func1(0xc000c88240)
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/extractor.go:479 +0x66
created by github.com/actiontech/dtle/internal/client/driver/mysql.(*Extractor).initiateStreaming
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/extractor.go:477 +0x3f

```

**Describe the results you expected:**

**Output of `./dtle version`:**

```
Dtle 9.9.9.9 (git: master 8cdbb04bdde164a69501975d5939316a251e7d24)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

#423 maybe the same error

**Additional details (log, config, job config etc):**

**Comment by Dinosauria** [comment]
ReplicateDoDb:
```
{
    "TableSchema":"",
    "TableSchemaRegex":"",
    "TableSchemaRename":"",
    "Tables":[
        {
            "TableName":"",
            "TableRegex":"",
            "TableRename":"",
            "where":""
        }
    ]
}
```

panic_log:

```
2019/04/02 10:03:15.696060 [DEBUG] [jobid:caeb62ca-f601-56cb-347a-ed4fe0376e2d] mysql.applier: no binlogEntry for 10s 
2019/04/02 10:03:24.289951 [DEBUG] [jobid:caeb62ca-f601-56cb-347a-ed4fe0376e2d] mysql.reader: query event: schema: test1, query: CREATE TABLE sbtest1 (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
k INTEGER UNSIGNED DEFAULT '0' NOT NULL,
c CHAR(120) DEFAULT '' NOT NULL,
pad CHAR(60) DEFAULT '' NOT NULL,
PRIMARY KEY (id)
) /*! ENGINE = innodb MAX_ROWS = 1000000 */ 
2019/04/02 10:03:24.291223 [DEBUG] [jobid:caeb62ca-f601-56cb-347a-ed4fe0376e2d] mysql.reader: ddl is create table 
2019/04/02 10:03:24.291505 [WARN] [jobid:caeb62ca-f601-56cb-347a-ed4fe0376e2d] error handle create table in binlog: GetTableColumns: table does not exists in sqle context. table: test1.sbtest1 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x89e3c6]

goroutine 738 [running]:
github.com/actiontech/dtle/internal/config/mysql.(*ColumnList).Names(0x0, 0xc0009dc000, 0x71, 0xc0009dc000)
	/universe/src/github.com/actiontech/dtle/internal/config/mysql/types.go:192 +0x26
github.com/actiontech/dtle/internal/config/mysql.(*ColumnList).String(0x0, 0x16a4022, 0x38)
	/universe/src/github.com/actiontech/dtle/internal/config/mysql/types.go:240 +0x2b
github.com/actiontech/dtle/internal/client/driver/mysql/binlog.(*BinlogReader).updateTableMeta(0xc00019d200, 0x0, 0xc0003358d7, 0x5, 0xc0001520fd, 0x7, 0x7, 0x0)
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/binlog/binlog_reader.go:1410 +0xde
github.com/actiontech/dtle/internal/client/driver/mysql/binlog.(*BinlogReader).handleEvent(0xc00019d200, 0xc0003e1680, 0xc000a2cc00, 0x0, 0x0)
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/binlog/binlog_reader.go:421 +0x1402
github.com/actiontech/dtle/internal/client/driver/mysql/binlog.(*BinlogReader).DataStreamEvents(0xc00019d200, 0xc000a2cc00, 0xc0003d9e60, 0xc000afb980)
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/binlog/binlog_reader.go:675 +0x228
github.com/actiontech/dtle/internal/client/driver/mysql.(*Extractor).StreamEvents(0xc0003d9e60, 0x1681312, 0x24)
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/extractor.go:871 +0x83
github.com/actiontech/dtle/internal/client/driver/mysql.(*Extractor).initiateStreaming.func1(0xc0003d9e60)
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/extractor.go:479 +0x66
created by github.com/actiontech/dtle/internal/client/driver/mysql.(*Extractor).initiateStreaming
	/universe/src/github.com/actiontech/dtle/internal/client/driver/mysql/extractor.go:477 +0x3f
```
