### ISSUE TITLE
dtle crash on deleting a running job

### ISSUE THREAD

**Issue by ffffwh** [actiontech/dtle#494]
version 2.19.07.0 2626641

> delelte 了一个running 的任务，然后dtle就挂了，启动不了。

```
2019/10/08 12:13:11.531841 [DEBUG] http: Request /v1/jobs (2.901869ms)
2019/10/08 12:13:28.935125 [DEBUG] http: Request /v1/job/ 48f9d3ea-5f4b-3874-685d-d2f19fcb3022 (134.531895ms) 2019/10/08 12:13:28.935195 [DEBUG] worker: Dequeued evaluation 3bfc7db1-815a-f5d3-771b-f81e63a9727e 2019/10/08 12:13:28.935551 [DEBUG] sched: <Eval '3bfc7db1-815a-f5d3-771b-f81e63a9727e' JobID: '48f9d3ea-5f4b-3874-685d-d2f19fcb3022'>: allocs: (place 0) (update 0) (migrate 0) (resume 0) (pause 0) (stop 0) (ignore 0) (lost 0)
2019/10/08 12:13:28.935634 [DEBUG] sched: <Eval '3bfc7db1-815a-f5d3-771b-f81e63a9727e' JobID: '48f9d3ea-5f4b-3874-685d-d2f19fcb3022'>: setting status to complete
2019/10/08 12:13:28.937695 [DEBUG] worker: Updated evaluation <Eval '3bfc7db1-815a-f5d3-771b-f81e63a9727e' JobID: '48f9d3ea-5f4b-3874-685d-d2f19fcb3022'> 2019/10/08 12:13:28.937912 [DEBUG] worker: ack for evaluation 3bfc7db1-815a-f5d3-771b-f81e63a9727e 2019/10/08 12:13:51.242591 [DEBUG] worker: Dequeued

 evaluation e773fb23-8bcc-6e7c-fbad-6098387f5130 2019/10/08 12:13:51.242587 [DEBUG] http: Request /v1/jobs (127.870869ms)
2019/10/08 12:13:51.248790 [DEBUG] sched: <Eval 'e773fb23-8bcc-6e7c-fbad-6098387f5130' JobID: '5e0bf037- b15d-92dc-82d2-b203a6d17766'>: allocs: (place 2) (update 0) (migrate 0) (resume 0) (pause 0) (stop 0) (ignore 0) (lost 0) 2019/10/08 12:13:51.252588 [DEBUG] worker: Submitted plan for evaluation e773fb23-8bcc-6e7c-fbad-6098387f5130 2019/10/08 12:13:51.253191 [DEBUG] sched: <Eval 'e773fb23-8bcc-6e7c-fbad-6098387f5130' JobID: '5e0bf037- b15d-92dc-82d2-b203a6d17766'>: setting status to complete 2019/10/08 12:13:51.254979 [DEBUG] worker: Updated evaluation <Eval 'e773fb23-8bcc-6e7c-fbad-6098387f5130' JobID: '5e0bf037-b15d-92dc-82d2-b203a6d17766'> 2019/10/08 12:13:51.255187 [DEBUG] worker: ack for evaluation e773fb23-8bcc-6e7c-fbad-6098387f5130 2019/10/08 12:14:10.532523 [DEBUG] Worker.SaveState: lock: 0xc00123cc40, 0xc0062d0420
2019/10/08 12:14:10.532679 [DEBUG] Worker.SaveState: after lock: 0xc00123cc40
2019/10/08 12:14:10.532719 [DEBUG] Worker.SaveState: after unlock: 0xc00123cc40
2019/10/08 12:14:12.863365 [WARN] server.heartbeat: node 'c78ae7c2-d36d-39b1-e887-e91cd4640855' TTL expired
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1065fa8]
goroutine 120 [running]: github.com/actiontech/dtle/internal/server. (*udupFSM).applyStatusUpdate(0xc0001e9db0, 0xc00042c091, 0x49, 0x85, 0x550ba, 0x0, 0x0)
/universe/src/github.com/actiontech/dtle/internal/server/

 fsm.go:330 +0x11c8 github.com/actiontech/dtle/internal/server. (*udupFSM).Apply(0xc0001e9db0, 0xc0032e0820, 0x2c1afc0, 0xc005813f08)
/universe/src/github.com/actiontech/dtle/internal/server/ fsm.go:135 +0x216
github.com/actiontech/dtle/vendor/github.com/hashicorp/raft. (*Raft).runFSM.func1(0xc0048aa350)
...
```

and crash after restarting dtle

```
2019/10/08 12:16:53.774749 [INFO] manager: cluster leadership acquired
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1065fa8]
goroutine 115 [running]: github.com/actiontech/dtle/internal/server. (*udupFSM).applyStatusUpdate(0xc000530d70, 0xc0002880a1, 0x49, 0x49, 0x550ba, 0x0, 0x0)
/universe/src/github.com/actiontech/dtle/internal/server/ fsm.go:330 +0x11c8 github.com/actiontech/dtle/internal/server. (*udupFSM).Apply(0xc000530d70, 0xc000d34270, 0x2c1afc0, 0xc000d6ff08)
/universe/src/github.com/actiontech/dtle/internal/server/ fsm.go:135 +0x216
github.com/actiontech/dtle/vendor/github.com/hashicorp/raft. (*Raft).runFSM.func1(0xc000102ff0)
```

[dtle-494-crash.log](https://github.com/actiontech/dtle/files/3701273/dtle-494-crash.log)

**Comment by ffffwh** [comment]
2.x deprecated.
