### ISSUE TITLE
kafka full replication job column type bit(1): kafka message return value always is false, 

### ISSUE THREAD

**Issue by asiroliu** [actiontech/dtle#534]
## Description
kafka full replication job column type bit(1): kafka message return value always is false

## Steps to reproduce the issue
1. create db and table 
```
create database action_db;
use action_db

create table bit_1_columns(id int(11) not null primary key,c_bit_1 bit(1) DEFAULT 1)ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
2. create kafka job
```
{
  "Name": "column_types_default_full_bit_1_columns",
  "Datacenters": [
    "dc1"
  ],
  "Tasks": [
    {
      "Type": "Src",
      "Driver": "MySQL",
      "NodeId": "da1c766d-b945-9ad4-a434-458d637f4420",
      "Config": {
        "ConnectionConfig": {
          "Host": "172.100.9.2",
          "Port": 3306,
          "User": "test_src",
          "Password": "test_src"
        },
        "ReplicateDoDb": [
          {
            "TableSchema": "action_db",
            "Tables": [
              {
                "TableName": "bit_1_columns"
              }
            ]
          }
        ]
      }
    },
    {
      "Type": "Dest",
      "Driver": "Kafka",
      "NodeId": "8db2080b-2753-9ce6-a264-45d3383ef35a",
      "Config": {
        "Topic": "dtle",
        "Brokers": [
          "172.100.9.21:9092"
        ],
        "Converter": "json"
      }
    }
  ]
}
```
3. insert some data
```
use action_db
insert into bit_1_columns values (0,0);
insert into bit_1_columns values (1,1);
insert into bit_1_columns values (2,NULL);
insert into bit_1_columns values (3,default);
```
4. get message from kafka
```
/kafka/bin/kafka-console-consumer.sh --bootstrap-server 172.100.9.21:9092 --from-beginning --property print.key=true --topic dtle.action_db.bit_1_columns
```

## Describe the results you received
```
value - payload - after = false
value - schema - fields["field": "before"] - fields["field": "c_bit_1"] = false
value - schema - fields["field": "after"] - fields["field": "c_bit_1"] ] = false
```
![image](https://user-images.githubusercontent.com/4859322/96404867-8e3aea80-120e-11eb-8767-a23af57cf154.png)

## Describe the results you expected
```
value - payload - after = true
value - schema - fields["field": "before"] - fields["field": "c_bit_1"] = true
value - schema - fields["field": "after"] - fields["field": "c_bit_1"] ] = true
```
![image](https://user-images.githubusercontent.com/4859322/96533708-edf1ce00-12c0-11eb-9b3a-339d6ebc6373.png)

## Output of `./dtle version`:**

```
NOMAD_VERSION=<0.11.1>
DTLE_VERSION=<9.9.9.9-master-f8a8a93>
```

## Additional information

(e.g. issue happens only occasionally)

**Comment by asiroliu** [comment]
version:
9.9.9.9-master-46fec54

源端dtle log：
```
2021-05-26T13:45:13.278+0800 [DEBUG] client.driver_mgr.dtle: panic: interface conversion: interface {} is nil, not types.BinaryLiteral: driver=dtle
2021-05-26T13:45:13.278+0800 [DEBUG] client.driver_mgr.dtle: : driver=dtle
2021-05-26T13:45:13.278+0800 [DEBUG] client.driver_mgr.dtle: goroutine 458 [running]:: driver=dtle
2021-05-26T13:45:13.278+0800 [DEBUG] client.driver_mgr.dtle: github.com/actiontech/dtle/drivers/mysql/kafka.kafkaColumnListToColDefs(0xc001cd9080, 0xc0006bde78, 0x3, 0x3, 0x3, 0xc0003bf640, 0x1c, 0xc000000041, 0x1a243a0): driver=dtle
2021-05-26T13:45:13.278+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/github.com/actiontech/dtle/drivers/mysql/kafka/kafka3.go:1115 +0xe6f: driver=dtle
2021-05-26T13:45:13.278+0800 [DEBUG] client.driver_mgr.dtle: github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).getOrSetTable(0xc00148ab40, 0xc000166ed0, 0x9, 0xc000166ec0, 0xd, 0xc0006b8900, 0x0, 0x0, 0x0): driver=dtle
2021-05-26T13:45:13.278+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/github.com/actiontech/dtle/drivers/mysql/kafka/kafka3.go:288 +0x30a: driver=dtle
2021-05-26T13:45:13.278+0800 [DEBUG] client.driver_mgr.dtle: github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).handleFullCopy(0xc00148ab40): driver=dtle
2021-05-26T13:45:13.278+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/github.com/actiontech/dtle/drivers/mysql/kafka/kafka3.go:334 +0x240: driver=dtle
2021-05-26T13:45:13.278+0800 [DEBUG] client.driver_mgr.dtle: created by github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).initiateStreaming: driver=dtle
2021-05-26T13:45:13.278+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/github.com/actiontech/dtle/drivers/mysql/kafka/kafka3.go:440 +0x71: driver=dtle
2021-05-26T13:45:13.286+0800 [DEBUG] client.driver_mgr: plugin process exited: driver=dtle path=/opt/dtle/usr/share/dtle/nomad-plugin/dtle pid=313 error="exit status 2"
```

**Comment by asiroliu** [comment]
# 验证
## version:
```
9.9.9.9-master-6f5dcaf
```
## reproduce:
1. full repl with default
```
drop table if exists bit_1_columns;
create table bit_1_columns(id int(11) not null primary key,c_bit_1 bit(1) DEFAULT 1)ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into bit_1_columns values (0,0);
insert into bit_1_columns values (1,1);
insert into bit_1_columns values (2,NULL);
insert into bit_1_columns values (3,default);
```
2. incr rple with default
```
drop table if exists bit_1_columns;
create table bit_1_columns(id int(11) not null primary key,c_bit_1 bit(1) DEFAULT 1)ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into bit_1_columns values (0,0);
insert into bit_1_columns values (1,1);
insert into bit_1_columns values (2,NULL);
insert into bit_1_columns values (3,default);

update bit_1_columns set c_bit_1=1 where id = 0;
update bit_1_columns set c_bit_1=0 where id = 1;

delete from bit_1_columns;
```
3. full repl without default
```
drop table if exists bit_1_columns;
create table bit_1_columns(id int(11) not null primary key,c_bit_1 bit(1))ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into bit_1_columns values (0,0);
insert into bit_1_columns values (1,1);
insert into bit_1_columns values (2,NULL);
```
4. incr reple without default
```
drop table if exists bit_1_columns;
create table bit_1_columns(id int(11) not null primary key,c_bit_1 bit(1))ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into bit_1_columns values (0,0);
insert into bit_1_columns values (1,1);
insert into bit_1_columns values (2,NULL);

update bit_1_columns set c_bit_1=1 where id = 0;
update bit_1_columns set c_bit_1=0 where id = 1;

delete from bit_1_columns;
```
5. the kafka massage is same as dbz's
