### ISSUE TITLE
a case of kafka panic

### ISSUE THREAD

**Issue by ffffwh** [actiontech/dtle#582]
version: 3.21.01.0 382c5357

复现场景
```hcl
        ReplicateDoDb = [{
          TableSchemaRegex = "db(.*)"
          TableSchemaRename = "db$${1}"
          Tables = [{
            TableName = "a"
          }]
        }]
# 即db开头的所有schema下的a表.
```

增量过程中创建新schema和table.

panic
```
    2021-02-05T18:42:22.578+0800 [DEBUG] client.driver_mgr.dtle: kafkaTransformDMLEventQueries: driver=dtle gno=2304 job=aa @module=dtle.kafka timestamp=2021-02-05T18:42:22.578+0800
    2021-02-05T18:42:22.580+0800 [DEBUG] client.driver_mgr.dtle: panic: runtime error: index out of range [0] with length 0: driver=dtle
    2021-02-05T18:42:22.580+0800 [DEBUG] client.driver_mgr.dtle: : driver=dtle
    2021-02-05T18:42:22.580+0800 [DEBUG] client.driver_mgr.dtle: goroutine 161 [running]:: driver=dtle
    2021-02-05T18:42:22.580+0800 [DEBUG] client.driver_mgr.dtle: github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).kafkaTransformDMLEventQueries(0xc00053d100, 0xc0003964e0, 0x1, 0x1, 0xc000000002, 0x577b56a): driver=dtle
    2021-02-05T18:42:22.580+0800 [DEBUG] client.driver_mgr.dtle: 	/Users/_/pro0/dtle2/drivers/mysql/kafka/kafka3.go:1041 +0x436a: driver=dtle
    2021-02-05T18:42:22.580+0800 [DEBUG] client.driver_mgr.dtle: github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).handleIncr.func1(0xc00038ef00, 0x577b56a): driver=dtle
    2021-02-05T18:42:22.580+0800 [DEBUG] client.driver_mgr.dtle: 	/Users/_/pro0/dtle2/drivers/mysql/kafka/kafka3.go:365 +0x68: driver=dtle
    2021-02-05T18:42:22.580+0800 [DEBUG] client.driver_mgr.dtle: github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).handleIncr(0xc00053d100): driver=dtle
    2021-02-05T18:42:22.580+0800 [DEBUG] client.driver_mgr.dtle: 	/Users/_/pro0/dtle2/drivers/mysql/kafka/kafka3.go:461 +0x742: driver=dtle
    2021-02-05T18:42:22.580+0800 [DEBUG] client.driver_mgr.dtle: created by github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).initiateStreaming: driver=dtle
    2021-02-05T18:42:22.580+0800 [DEBUG] client.driver_mgr.dtle: 	/Users/_/pro0/dtle2/drivers/mysql/kafka/kafka3.go:475 +0x96: driver=dtle
```

**Comment by asiroliu** [comment]
# version:
```
3.21.01.0-3.21.01.0-382c535
```
# reproduce:
1. prepare date
```sql
mysql> create database test_1;
Query OK, 1 row affected (0.01 sec)

mysql> create database test_2;
Query OK, 1 row affected (0.00 sec)

mysql> create database test_3;
Query OK, 1 row affected (0.00 sec)
```
```bash
shell> sysbench /usr/share/sysbench/oltp_insert.lua --range_size=100 --table_size=2100 --tables=1 --mysql-host=172.100.9.1 --mysql-port=3307 --mysql-user=test --mysql-password=test --mysql-db=test_1 prepare

shell> sysbench /usr/share/sysbench/oltp_insert.lua --range_size=100 --table_size=2100 --tables=1 --mysql-host=172.100.9.1 --mysql-port=3307 --mysql-user=test --mysql-password=test --mysql-db=test_2 prepare

shell> sysbench /usr/share/sysbench/oltp_insert.lua --range_size=100 --table_size=2100 --tables=1 --mysql-host=172.100.9.1 --mysql-port=3307 --mysql-user=test --mysql-password=test --mysql-db=test_3 prepare
```
2. create job
```hcl
job "test1" {
  datacenters = ["dc1"]
  type = "service"

  group "Src" {
    affinity {
      attribute = "${node.unique.name}"
      value = "dtle-1"
      }
    task "src" {
      driver = "dtle"
      config {
        ReplicateDoDb = [{
          TableSchemaRegex = "test(.*)"
          TableSchemaRename = "test$${1}"
          Tables = [{
            TableName = "sbtest1"
          }]
        }]
        ConnectionConfig = {
          Host = "172.100.9.1"
          Port = 3307
          User = "test_src"
          Password = "test_src"
        }
      }
    }
  }
  group "Dest" {
    affinity {
      attribute = "${node.unique.name}"
      value = "dtle-2"
      }
		task "dest" {
      driver = "dtle"
      config {
        KafkaConfig = {
          Topic = "kafka1"
          Brokers = ["172.100.9.21:9092"]
          Converter = "json"
        }
      }
    }
  }
}
```
3. create database
```sql
mysql>  create database test_4;
Query OK, 1 row affected (0.01 sec)
```
4. check log
```
2021-02-06T22:11:20.369+0800 [DEBUG] client.driver_mgr.dtle: panic: runtime error: index out of range [0] with length 0: driver=dtle
2021-02-06T22:11:20.369+0800 [DEBUG] client.driver_mgr.dtle: : driver=dtle
2021-02-06T22:11:20.369+0800 [DEBUG] client.driver_mgr.dtle: goroutine 127 [running]:: driver=dtle
2021-02-06T22:11:20.369+0800 [DEBUG] client.driver_mgr.dtle: github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).kafkaTransformDMLEventQueries(0xc00002ef00, 0xc0006ba0b8, 0x1, 0x1, 0xc000000002, 0x1b7c934): driver=dtle
2021-02-06T22:11:20.369+0800 [DEBUG] client.driver_mgr.dtle: 	/universe/src/github.com/actiontech/dtle/drivers/mysql/kafka/kafka3.go:1041 +0x432c: driver=dtle
2021-02-06T22:11:20.369+0800 [DEBUG] client.driver_mgr.dtle: github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).handleIncr.func1(0xc00068e420, 0x1b7c934): driver=dtle
2021-02-06T22:11:20.369+0800 [DEBUG] client.driver_mgr.dtle: 	/universe/src/github.com/actiontech/dtle/drivers/mysql/kafka/kafka3.go:365 +0x68: driver=dtle
2021-02-06T22:11:20.369+0800 [DEBUG] client.driver_mgr.dtle: github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).handleIncr(0xc00002ef00): driver=dtle
2021-02-06T22:11:20.369+0800 [DEBUG] client.driver_mgr.dtle: 	/universe/src/github.com/actiontech/dtle/drivers/mysql/kafka/kafka3.go:461 +0x742: driver=dtle
2021-02-06T22:11:20.369+0800 [DEBUG] client.driver_mgr.dtle: created by github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).initiateStreaming: driver=dtle
2021-02-06T22:11:20.369+0800 [DEBUG] client.driver_mgr.dtle: 	/universe/src/github.com/actiontech/dtle/drivers/mysql/kafka/kafka3.go:475 +0x96: driver=dtle
2021-02-06T22:11:20.377+0800 [DEBUG] client.driver_mgr: plugin process exited: driver=dtle path=/opt/dtle/usr/share/dtle/nomad-plugin/dtle pid=238 error="exit status 2"
```

**Comment by asiroliu** [comment]
# version:
```
9.9.9.9-master-a0a374d
```
# reproduce:
1. prepare date
```sql
mysql> create database test_1;
Query OK, 1 row affected (0.01 sec)

mysql> create database test_2;
Query OK, 1 row affected (0.00 sec)

mysql> create database test_3;
Query OK, 1 row affected (0.00 sec)
```
```bash
shell> sysbench /usr/share/sysbench/oltp_insert.lua --range_size=100 --table_size=2100 --tables=1 --mysql-host=172.100.9.1 --mysql-port=3307 --mysql-user=test --mysql-password=test --mysql-db=test_1 prepare

shell> sysbench /usr/share/sysbench/oltp_insert.lua --range_size=100 --table_size=2100 --tables=1 --mysql-host=172.100.9.1 --mysql-port=3307 --mysql-user=test --mysql-password=test --mysql-db=test_2 prepare

shell> sysbench /usr/share/sysbench/oltp_insert.lua --range_size=100 --table_size=2100 --tables=1 --mysql-host=172.100.9.1 --mysql-port=3307 --mysql-user=test --mysql-password=test --mysql-db=test_3 prepare
```
2. create job
```hcl
job "test1" {
  datacenters = ["dc1"]
  type = "service"

  group "Src" {
    affinity {
      attribute = "${node.unique.name}"
      value = "dtle-1"
      }
    task "src" {
      driver = "dtle"
      config {
        ReplicateDoDb = [{
          TableSchemaRegex = "test(.*)"
          TableSchemaRename = "test$${1}"
          Tables = [{
            TableName = "sbtest1"
          }]
        }]
        ConnectionConfig = {
          Host = "172.100.9.1"
          Port = 3307
          User = "test_src"
          Password = "test_src"
        }
      }
    }
  }
  group "Dest" {
    affinity {
      attribute = "${node.unique.name}"
      value = "dtle-2"
      }
		task "dest" {
      driver = "dtle"
      config {
        KafkaConfig = {
          Topic = "kafka1"
          Brokers = ["172.100.9.21:9092"]
          Converter = "json"
        }
      }
    }
  }
}
```
3. create database
```sql
mysql>  create database test_4;
Query OK, 1 row affected (0.01 sec)
```
4. check log
```
2021-02-06T22:43:39.150+0800 [DEBUG] client.driver_mgr.dtle: query event: driver=dtle @module=reader job=test1 query="create database test_4" schema=test_4 timestamp=2021-02-06T22:43:39.150+0800
2021-02-06T22:43:39.151+0800 [DEBUG] client.driver_mgr.dtle: ddl schema mapping: driver=dtle to=test_4 @module=reader from=test_4 job=test1 timestamp=2021-02-06T22:43:39.150+0800
2021-02-06T22:43:39.151+0800 [INFO]  client.driver_mgr.dtle: NewQueryEventAffectTable. found empty schema or table.: driver=dtle @module=reader job=test1 query="CREATE DATABASE `test_4`" schema=test_4 table= timestamp=2021-02-06T22:43:39.150+0800
2021-02-06T22:43:39.151+0800 [DEBUG] client.driver_mgr.dtle: sendEntry: driver=dtle @module=reader gno=16 job=test1 timestamp=2021-02-06T22:43:39.150+0800
2021-02-06T22:43:39.151+0800 [DEBUG] client.driver_mgr.dtle: extractor. incr. send by GroupLimit: driver=dtle entriesSize=101 groupMaxSize=1 job=test1 @module=dtle.extractor Entries.len=1 timestamp=2021-02-06T22:43:39.150+0800
2021-02-06T22:43:39.151+0800 [DEBUG] client.driver_mgr.dtle: publish.before: driver=dtle n=1 @module=dtle.extractor gno=16 job=test1 timestamp=2021-02-06T22:43:39.151+0800
2021-02-06T22:43:39.151+0800 [DEBUG] client.driver_mgr.dtle: publish: driver=dtle job=test1 len=103 subject=test1_incr_hete @module=dtle.extractor timestamp=2021-02-06T22:43:39.151+0800
```
```
2021-02-06T22:43:39.151+0800 [DEBUG] client.driver_mgr.dtle: kafkaTransformDMLEventQueries: driver=dtle @module=dtle.kafka gno=16 job=test1 timestamp=2021-02-06T22:43:39.151+0800
2021-02-06T22:43:39.151+0800 [DEBUG] client.driver_mgr.dtle: kafkaTransformDMLEventQueries: empty table name: driver=dtle @module=dtle.kafka job=test1 query="CREATE DATABASE `test_4`" type=0 timestamp=2021-02-06T22:43:39.151+0800
2021-02-06T22:43:39.152+0800 [DEBUG] client.driver_mgr.dtle: sent msgs: driver=dtle @module=dtle.kafka job=test1 timestamp=2021-02-06T22:43:39.151+0800
2021-02-06T22:43:39.152+0800 [DEBUG] client.driver_mgr.dtle: kafka. updateGtidString: driver=dtle @module=dtle.kafka gtid=00003307-0000-0000-0000-000000003307:1-16,5ed27737-6889-11eb-925f-0242ac640901:1-16 job=test1 timestamp=2021-02-06T22:43:39.151+0800
2021-02-06T22:43:39.152+0800 [DEBUG] client.driver_mgr.dtle: kafka: after kafkaTransformDMLEventQueries: driver=dtle job=test1 @module=dtle.kafka timestamp=2021-02-06T22:43:39.151+0800
2021-02-06T22:43:43.180+0800 [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=1.02465ms
2021-02-06T22:43:51.816+0800 [DEBUG] client.driver_mgr.dtle: TimestampContext.GetDelay: driver=dtle @module=dtle.kafka delay=0 job=test1 timestamp=2021-02-06T22:43:51.816+0800
2021-02-06T22:43:51.829+0800 [DEBUG] client.driver_mgr.dtle: SaveGtidForJob: driver=dtle gtid=00003307-0000-0000-0000-000000003307:1-16,5ed27737-6889-11eb-925f-0242ac640901:1-16 job=test1 @module=dtle.kaf
```
