### ISSUE TITLE
insert text type data causes DTLE panic in Kafka incremental stage 

### ISSUE THREAD

**Issue by asiroliu** [actiontech/dtle#712]
## Description
insert text type data causes DTLE panic in Kafka incremental stage 

## Steps to reproduce the issue
1. create kafka job
```
{
  "Name": "column_types_incr_text_columns",
  "Datacenters": [
    "dc1"
  ],
  "Tasks": [
    {
      "Type": "Src",
      "Driver": "MySQL",
      "NodeId": "48dac7f2-14aa-2c54-2284-42fdf47a3bf4",
      "Config": {
        "ConnectionConfig": {
          "Host": "172.100.9.2",
          "Port": 3306,
          "User": "test_src",
          "Password": "test_src"
        },
        "ReplicateDoDb": [
          {
            "TableSchema": "action_db",
            "Tables": [
              {
                "TableName": "text_columns"
              }
            ]
          }
        ]
      }
    },
    {
      "Type": "Dest",
      "Driver": "Kafka",
      "NodeId": "76346fd2-0b69-4868-0859-5c04e0f59a1e",
      "Config": {
        "Topic": "dtle",
        "Brokers": [
          "172.100.9.21:9092"
        ],
        "Converter": "json"
      }
    }
  ]
}
```
2.  insert text type data
```
create database action_db;
create table text_columns(id int(11) not null primary key,c_text text)ENGINE=InnoDB DEFAULT CHARSET=utf8;
insert into text_columns values (1,'');
```
3. check dest dtle log
```
2021-06-23T17:10:42.300+0800 [DEBUG] client.driver_mgr.dtle: panic: interface conversion: interface {} is string, not []uint8: driver=dtle
2021-06-23T17:10:42.300+0800 [DEBUG] client.driver_mgr.dtle: : driver=dtle
2021-06-23T17:10:42.300+0800 [DEBUG] client.driver_mgr.dtle: goroutine 278 [running]:: driver=dtle
2021-06-23T17:10:42.300+0800 [DEBUG] client.driver_mgr.dtle: github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).kafkaTransformDMLEventQueries(0xc000452c60, 0xc000712068, 0x1, 0x1, 0xc000000002, 0x1d7a4fa): driver=dtle
2021-06-23T17:10:42.300+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/github.com/actiontech/dtle/drivers/mysql/kafka/kafka3.go:923 +0x473c: driver=dtle
2021-06-23T17:10:42.300+0800 [DEBUG] client.driver_mgr.dtle: github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).handleIncr.func1(0xc0001b7620, 0x1d7a4fa): driver=dtle
2021-06-23T17:10:42.300+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/github.com/actiontech/dtle/drivers/mysql/kafka/kafka3.go:375 +0x68: driver=dtle
2021-06-23T17:10:42.300+0800 [DEBUG] client.driver_mgr.dtle: github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).handleIncr(0xc000452c60): driver=dtle
2021-06-23T17:10:42.300+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/github.com/actiontech/dtle/drivers/mysql/kafka/kafka3.go:437 +0x724: driver=dtle
2021-06-23T17:10:42.300+0800 [DEBUG] client.driver_mgr.dtle: created by github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).initiateStreaming: driver=dtle
2021-06-23T17:10:42.300+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/github.com/actiontech/dtle/drivers/mysql/kafka/kafka3.go:450 +0x96: driver=dtle
2021-06-23T17:10:42.307+0800 [ERROR] client.driver_mgr: error receiving stream from TaskStats driver RPC, closing stream: driver=dtle error="rpc error: code = Unavailable desc = transport is closing"
2021-06-23T17:10:42.307+0800 [DEBUG] client.driver_mgr: plugin process exited: driver=dtle path=/opt/dtle/usr/share/dtle/nomad-plugin/dtle pid=283 error="exit status 2"
2021-06-23T17:10:42.308+0800 [WARN]  client.driver_mgr: received fingerprint error from driver: driver=dtle error="plugin is shut down"
```

## Output of `./dtle version`:**

```
9.9.9.9-master-138cf0f
```

## Additional information

(e.g. issue happens only occasionally)

**Comment by ffffwh** [comment]
9ecde819
