### ISSUE TITLE
panic: send on closed channel: driver=dtle

### ISSUE THREAD

**Issue by ffffwh** [actiontech/dtle#735]
version 3.21.06.1

```
2021-07-09T17:52:26.423+0800 [INFO]  client.driver_mgr.dtle: Shutting down: driver=dtle @module=dtle.kafka job=kafka1 timestamp=2021-07-09T17:52:26.415+0800
2021-07-09T17:52:26.423+0800 [DEBUG] client.driver_mgr.dtle: panic: send on closed channel: driver=dtle
2021-07-09T17:52:26.423+0800 [DEBUG] client.driver_mgr.dtle: : driver=dtle
2021-07-09T17:52:26.423+0800 [DEBUG] client.driver_mgr.dtle: goroutine 171 [running]:: driver=dtle
2021-07-09T17:52:26.423+0800 [DEBUG] client.driver_mgr.dtle: github.com/actiontech/dtle/drivers/mysql/kafka.(*KafkaRunner).initiateStreaming.func3(0xc001206140): driver=dtle
2021-07-09T17:52:26.423+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/github.com/actiontech/dtle/drivers/mysql/kafka/kafka3.go:522 +0x1c9: driver=dtle
2021-07-09T17:52:26.423+0800 [DEBUG] client.driver_mgr.dtle: github.com/nats-io/go-nats.(*Conn).waitForMsgs(0xc000160b00, 0xc0003206c0): driver=dtle
2021-07-09T17:52:26.423+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/github.com/actiontech/dtle/vendor/github.com/nats-io/go-nats/nats.go:2047 +0x364: driver=dtle
2021-07-09T17:52:26.423+0800 [DEBUG] client.driver_mgr.dtle: created by github.com/nats-io/go-nats.(*Conn).subscribe: driver=dtle
2021-07-09T17:52:26.423+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/github.com/actiontech/dtle/vendor/github.com/nats-io/go-nats/nats.go:2811 +0x490: driver=dtle
```

around
```
select {
case <-kr.shutdownCh:
	return
case kr.chBinlogEntries <- &binlogEntries:
	...
}
```

**Comment by ffffwh** [comment]
`Shutdown()`中把`shutdownCh`和`chBinlogEntries`都`close()`了.

当select中的多个条件同时满足时, 会随机选择一条路径. 排在前面的shutdownCh case并不会优先执行.

对于`case item <-chMaybeClosed`这种从chan中读取情况, 还可以判断item是否为nil. 对于写入的情况, 并没有特别好的办法.

**Comment by ffffwh** [comment]
https://stackoverflow.com/a/8593986/883077

> It's OK to leave a Go channel open forever and never close it. When the channel is no longer used, it will be garbage collected.
>
> > Note that it is only necessary to close a channel if the receiver is looking for a close. Closing the channel is a control signal on the channel indicating that no more data follows.
