### ISSUE TITLE
Oracle to MySQL - DDL - data type TIMESTAMP(9) panic

### ISSUE THREAD

**Issue by asiroliu** [actiontech/dtle#818]
## Description
Oracle to MySQL - DDL - data type TIMESTAMP(9) panic

## Steps to reproduce the issue
1.  oracle execute sql
```
CREATE TABLE TEST.TIMESTAMP_COLUMNS(col1 INT, col2 TIMESTAMP(9));
```
2.  dest dtle log
```
2021-11-26T11:20:50.782+0800 [DEBUG] client.driver_mgr.dtle: not dml: driver=dtle job=abc-migration query="CREATE TABLE TEST.TIMESTAMP_COLUMNS (COL1 INT,COL2 DATETIME(9))" @module=dtle.ApplierOracle.ApplyBinlogEvent timestamp=2021-11-26T11:20:50.782+0800
2021-11-26T11:20:50.782+0800 [DEBUG] client.driver_mgr.dtle: reset tableItem: driver=dtle @module=dtle.ApplierOracle.ApplyBinlogEvent job=abc-migration schema=TEST table=TIMESTAMP_COLUMNS timestamp=2021-11-26T11:20:50.782+0800
2021-11-26T11:20:50.782+0800 [ERROR] client.driver_mgr.dtle: Exec sql error: driver=dtle @module=dtle.ApplierOracle.ApplyBinlogEvent err="tx.Exec. gno 0 iEvent 0 queryBegin CREATE TAB workerIdx 0: Error 1426: Too-big precision 9 specified for 'COL2'. Maximum is 6." job=abc-migration timestamp=2021-11-26T11:20:50.782+0800
2021-11-26T11:20:50.784+0800 [DEBUG] client.driver_mgr.dtle: panic: runtime error: invalid memory address or nil pointer dereference: driver=dtle
2021-11-26T11:20:50.784+0800 [DEBUG] client.driver_mgr.dtle: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12c245c]: driver=dtle
2021-11-26T11:20:50.784+0800 [DEBUG] client.driver_mgr.dtle: : driver=dtle
2021-11-26T11:20:50.784+0800 [DEBUG] client.driver_mgr.dtle: goroutine 272 [running]:: driver=dtle
2021-11-26T11:20:50.784+0800 [DEBUG] client.driver_mgr.dtle: github.com/actiontech/dtle/drivers/mysql/mysql/oracle/applier.(*ApplierOracleIncr).heterogeneousReplay.func1(0xc000658e00): driver=dtle
2021-11-26T11:20:50.784+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/github.com/actiontech/dtle/drivers/mysql/mysql/oracle/applier/applier_oracle_incr.go:133 +0x15c: driver=dtle
2021-11-26T11:20:50.785+0800 [DEBUG] client.driver_mgr.dtle: created by github.com/actiontech/dtle/drivers/mysql/mysql/oracle/applier.(*ApplierOracleIncr).heterogeneousReplay: driver=dtle
2021-11-26T11:20:50.785+0800 [DEBUG] client.driver_mgr.dtle:    /universe/src/github.com/actiontech/dtle/drivers/mysql/mysql/oracle/applier/applier_oracle_incr.go:121 +0xd0: driver=dtle
2021-11-26T11:20:50.791+0800 [DEBUG] client.driver_mgr.stdio: received EOF, stopping recv loop: driver=dtle err="rpc error: code = Unavailable desc = transport is closing"
2021-11-26T11:20:50.791+0800 [ERROR] client.driver_mgr: error receiving stream from TaskStats driver RPC, closing stream: driver=dtle error="rpc error: code = Unavailable desc = transport is closing"
2021-11-26T11:20:50.791+0800 [DEBUG] client.driver_mgr: plugin process exited: driver=dtle path=/opt/dtle/usr/share/dtle/nomad-plugin/dtle pid=362 error="exit status 2"
2021-11-26T11:20:50.791+0800 [DEBUG] client.alloc_runner.task_runner: driver plugin has shutdown; attempting to recover task: alloc_id=30ca80ee-5a63-8302-e7ff-a9168e4601ae task=dest driver=dtle
2021-11-26T11:20:50.791+0800 [WARN]  client.driver_mgr: received fingerprint error from driver: driver=dtle error="plugin is shut down"
2021-11-26T11:20:50.791+0800 [WARN]  client.driver_mgr: failed to reattach to plugin, starting new instance: driver=dtle err="singleton plugin exited"
``` 
3. https://dev.mysql.com/doc/refman/5.7/en/date-and-time-type-syntax.html
mysql DATETIME[(fsp)], fsp value in the range from 0 to 6

## Output of `./dtle version`:**

```
9.9.9.9-oracle_demo-ff1407f
```

**Comment by asiroliu** [comment]
version:
```
9.9.9.9-oracle_demo-1ffa8bf
```
oracle sql:
```
CREATE TABLE TEST.TIMESTAMP_COLUMNS(col1 INT, col2 TIMESTAMP(9));
```
mysql general log
```
2021-12-24T02:37:19.803824Z	   13 Query	START TRANSACTION
2021-12-24T02:37:19.804601Z	   13 Query	CREATE TABLE `TEST`.`TIMESTAMP_COLUMNS` (`COL1` INT,`COL2` DATETIME(6)) DEFAULT CHARACTER SET=utf8
2021-12-24T02:37:19.808518Z	   13 Query	COMMIT
```
dtle log
```
2021-12-24T10:37:19.804+0800 [DEBUG] client.driver_mgr.dtle: binlogEntry.Events: driver=dtle @module=dtle.ApplierOracle.ApplyBinlogEvent event="map[ColumnCount:0 CurrentSchema:TEST DML:0 DatabaseName:TEST LogPos:0 NewColumnValues:<nil> Query:CREATE TABLE `TEST`.`TIMESTAMP_COLUMNS` (`COL1` INT,`COL2` DATETIME(6)) DEFAULT CHARACTER SET=utf8 Table:<nil> TableName:TIMESTAMP_COLUMNS Timestamp:0 WhereColumnValues:<nil>]" gno=0 job=aaa-migration timestamp=2021-12-24T10:37:19.804+0800
2021-12-24T10:37:19.804+0800 [DEBUG] client.driver_mgr.dtle: not dml: driver=dtle @module=dtle.ApplierOracle.ApplyBinlogEvent job=aaa-migration query="CREATE TABLE `TEST`.`TIMESTAMP_COLUMNS` (`COL1` INT,`COL2` DATETIME(6)) DEFAULT CHARACTER SET=utf8" timestamp=2021-12-24T10:37:19.804+0800
2021-12-24T10:37:19.804+0800 [DEBUG] client.driver_mgr.dtle: reset tableItem: driver=dtle schema=TEST table=TIMESTAMP_COLUMNS @module=dtle.ApplierOracle.ApplyBinlogEvent job=aaa-migration timestamp=2021-12-24T10:37:19.804+0800
```
